import json
from flask import request


from outside_apis.openai_api import generate_image


def process_request(request: request) -> dict:
    '''
    Process the incoming data of the Telegram request

    Parameters:
        - request(falsk.request)

    Returns:
        - dict of these key and value 
        {
            'is_text': is_text,
            'is_chat_deleted': is_chat_deleted,
            'sender_id': sender_id,
            'message': message,
            'secret_token': secret_token,
            'first_name': first_name
        }
    '''
    body = request.get_json()
    print(body)
    headers = request.headers
    secret_token = headers['X-Telegram-Bot-Api-Secret-Token']

    message = ''
    is_bot = True
    is_text = False
    first_name = ''
    sender_id = None

    if 'message' in body.keys():
        sender_id = body['message']['from']['id']
        first_name = body['message']['from']['first_name']
        is_bot = body['message']['from']['is_bot']

        if 'text' in body['message'].keys():
            message += body['message']['text']
            is_text = True

    return {
        'is_text': is_text,
        'sender_id': sender_id,
        'message': message,
        'secret_token': secret_token,
        'first_name': first_name,
        'is_bot': is_bot
    }


def generate_response(message: str) -> str:
    '''
    Process the incoming message for different command and generate a response string

    Parameters:
        - message(str): incoming message from Telegram

    Returns:
        - str: formated response for the command
    '''
    if message == '/contactme':
        return {
            'message': 'You can reach out to me here: https://rajkkapadia-portfolio.onrender.com/',
            'openai': False
        }
    elif message == '/youtube':
        return {
            'message': 'You can watch my video tutorials here: https://www.youtube.com/channel/UCOT01XvBSj12xQsANtTeAcQ',
            'openai': False
        }
    elif message == '/github':
        return {
            'message': 'You can get helpful piece of code here: https://github.com/RajKKapadia',
            'openai': False
        }
    elif message == '/buyacoffee':
        return {
            'message': 'If you like my work please consider buying me a coffee here: https://www.buymeacoffee.com/rajkkapadia',
            'openai': False
        }
    elif message == '/help':
        return {
            'message': 'Provide a detailed description of an image, get back the image generated by AI. :-)',
            'openai': False
        }
    elif message == '/start':
        return {
            'message': 'Hi, this is a chat-bot that uses OpenAI Dall-E2, developed by me with love. I will not spam you for sure.',
            'openai': False
        }
    elif len(message) < 4:
        return {
            'message': 'Hey, it seems very few words, please write as much detail as you can, it will be always better with more words.',
            'openai': False
        }
    else:
        result = generate_image(message)
        if result['status'] == 1:
            return {
            'message': result['url'],
            'openai': True
        }
        else:
            return {
            'message': 'Sorry, I am out of service at this moment.',
            'openai': False
        }
